// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DepartmentParticipation struct {
	Department    string `json:"department"`
	AttendeeCount int32  `json:"attendee_count"`
	IsExternal    bool   `json:"is_external"`
}

type Event struct {
	EventID             string                     `json:"eventID"`
	Subject             string                     `json:"subject"`
	Start               string                     `json:"start"`
	End                 string                     `json:"end"`
	DurationMinutes     int32                      `json:"durationMinutes"`
	DepartmentBreakdown []*DepartmentParticipation `json:"department_breakdown"`
	FormParticipants    *string                    `json:"form_participants,omitempty"`
	FormDepartment      *string                    `json:"form_department,omitempty"`
}

type Query struct {
}

type Room struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Email  string   `json:"email"`
	Events []*Event `json:"events"`
}

func (Room) IsEntity() {}
