// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BeverageCount struct {
	ID             string    `json:"id"`
	TotalBeverages int32     `json:"totalBeverages"`
	Timestamp      time.Time `json:"timestamp"`
}

type BeverageDetail struct {
	ID           string    `json:"id"`
	BeverageName string    `json:"beverageName"`
	Count        int32     `json:"count"`
	Timestamp    time.Time `json:"timestamp"`
}

type Floor struct {
	ID       string     `json:"id"`
	Machines []*Machine `json:"machines"`
}

func (Floor) IsEntity() {}

type Machine struct {
	ID              string            `json:"id"`
	Name            string            `json:"name"`
	BeverageCounts  []*BeverageCount  `json:"beverageCounts"`
	BeverageDetails []*BeverageDetail `json:"beverageDetails"`
}

func (Machine) IsEntity() {}

type Query struct {
}
