// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BeverageCount struct {
	ID             string    `json:"id"`
	MachineID      *Machine  `json:"machineId"`
	TotalBeverages int32     `json:"totalBeverages"`
	Timestamp      time.Time `json:"timestamp"`
}

type BeverageDetail struct {
	ID           string    `json:"id"`
	MachineID    *Machine  `json:"machineId"`
	BeverageName string    `json:"beverageName"`
	Count        int32     `json:"count"`
	Timestamp    time.Time `json:"timestamp"`
}

type Machine struct {
	MachineID       string            `json:"machineId"`
	MachineName     string            `json:"machineName"`
	BeverageCounts  []*BeverageCount  `json:"beverageCounts"`
	BeverageDetails []*BeverageDetail `json:"beverageDetails"`
}

type Query struct {
}
