package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/LarsDepuydt/masterthesis-api-aggregation/service-doorcounters/graph/model"
)

// FindBuildingByID is the resolver for the findBuildingByID field.
func (r *entityResolver) FindBuildingByID(ctx context.Context, id string) (*model.Building, error) {
	panic(fmt.Errorf("not implemented: FindBuildingByID - findBuildingByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
