// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Query struct {
}

type Sensor struct {
	ExternalID string   `json:"externalID"`
	SourcePath string   `json:"sourcePath"`
	Unit       string   `json:"unit"`
	Values     []*Value `json:"values"`
}

type Value struct {
	Timestamp time.Time `json:"timestamp"`
	Value     float64   `json:"value"`
}
