// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Building struct {
	ID        string      `json:"id"`
	Entrances []*Entrence `json:"entrances"`
}

func (Building) IsEntity() {}

type Entrence struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	TelemetryData []*TelemetryData `json:"telemetryData"`
}

type Query struct {
}

type TelemetryData struct {
	Timestamp string `json:"timestamp"`
	Value     *int32 `json:"value,omitempty"`
}
