// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type TelemetryData struct {
	Timestamp string `json:"timestamp"`
	DoorA     *int32 `json:"doorA,omitempty"`
	DoorB     *int32 `json:"doorB,omitempty"`
	DoorC     *int32 `json:"doorC,omitempty"`
}
