// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Building struct {
	ID       string   `json:"id"`
	Address  string   `json:"address"`
	City     string   `json:"city"`
	Property string   `json:"property"`
	Floors   []*Floor `json:"floors"`
}

type Floor struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Rooms        []*Room `json:"rooms"`
	FloorplanURL string  `json:"floorplanUrl"`
}

type Query struct {
}

type Room struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	Area          float64 `json:"area"`
	Circumference float64 `json:"circumference"`
}
